domain: ilroccolobrisighella.com
url: https://roccolo.github.io
baseurl: ""

title: Il Roccolo Brisighella
email: francesca.olivi98@gmail.com
author: Francesca Olivi

lang: en

plugins:
  - jekyll-seo-tag

color: "#13ccf9"
# disqus:
#   shortname: example-com
#
rrss:
  email: "example@example.cl"
  telegram: "https://t.me/"
  discord: "https://discord.com/"
