domain: ilroccolobrisighella.com
url: https://roccolo.github.io
baseurl: ""

title: Il Roccolo Brisighella
email: francesca.olivi98@gmail.com
author: Francesca Olivi

lang: en

plugins:
  - jekyll-seo-tag

color: "#13ccf9"
# disqus:
#   shortname: example-com
#
rrss:
  email: "mailto:francesca.olivi98@gmail.com"
  telegram: "https://t.me/Fraolivi"
  whatsapp: "https://wa.me/00393280546712>"
